# Documentation for all configuration options:
# https://help.github.com/github/administering-a-repository/configuration-options-for-dependency-updates
version: 2
updates:
  - package-ecosystem: "maven"
    directory: "/"
    schedule:
      interval: "daily"
    ignore:
      - dependency-name: "org.activiti:activiti-dependencies"
      - dependency-name: "org.activiti:activiti-api-dependencies"
      - dependency-name: "org.activiti:activiti-core-dependencies"
      - dependency-name: "org.activiti:activiti-core-common-dependencies"
      - dependency-name: "org.activiti.cloud:activiti-cloud-audit-dependencies"
      - dependency-name: "org.activiti.cloud:activiti-cloud-api-dependencies"
      - dependency-name: "org.activiti.cloud:activiti-cloud-parent"
      - dependency-name: "org.activiti.cloud:activiti-cloud-build-parent"
      - dependency-name: "org.activiti.cloud:activiti-cloud-build-dependencies-parent"
      - dependency-name: "org.activiti.cloud:activiti-cloud-connectors-dependencies"
      - dependency-name: "org.activiti.cloud:activiti-cloud-messages-dependencies"
      - dependency-name: "org.activiti.cloud:activiti-cloud-modeling-dependencies"
      - dependency-name: "org.activiti.cloud:activiti-cloud-notifications-graphql-dependencies"
      - dependency-name: "org.activiti.cloud:activiti-cloud-query-dependencies"
      - dependency-name: "org.activiti.cloud:activiti-cloud-runtime-bundle-dependencies"
      - dependency-name: "org.activiti.cloud:activiti-cloud-acceptance-tests-dependencies"
      - dependency-name: "org.activiti.cloud:activiti-cloud-service-common-dependencies"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
  - package-ecosystem: "github-actions"
    directory: "/.github/actions/check-service-health"
    schedule:
      interval: "weekly"
  - package-ecosystem: "github-actions"
    directory: "/.github/actions/setup-env-for-broker"
    schedule:
      interval: "weekly"
