apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ template "fullname" . }}
  labels:
    draft: {{ default "draft-app" .Values.draft }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
spec:
  replicas: {{ .Values.replicaCount }}
  template:
    metadata:
      labels:
        draft: {{ default "draft-app" .Values.draft }}
        app: {{ template "fullname" . }}
{{- if .Values.podAnnotations }}
      annotations:
{{ toYaml .Values.podAnnotations | indent 8 }}
{{- end }}
    spec:
      containers:
      - name: {{ .Chart.Name }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        env:
        - name: JAVA_OPTS
          value: "-Xmx{{ .Values.javaOpts.xmx }} -Xms{{ .Values.javaOpts.xms }} {{ .Values.javaOpts.other}}"
        - name: SPRING_APPLICATION_NAME
{{- if .Values.service.name }}
          value: "{{ .Values.service.name }}"
{{- else }}
          value: {{ template "fullname" . }}
{{- end }}
        - name: SPRING_RABBITMQ_HOST
        {{- if .Values.global.rabbitmq.host.value }}
          value: "{{ .Values.global.rabbitmq.host.value }}"
        {{ else }}
          value: "{{ .Release.Name }}-rabbitmq"
        {{ end }}
        - name: SPRING_RABBITMQ_USERNAME
          value: {{ .Values.global.rabbitmq.username.value }}
        - name: SPRING_RABBITMQ_HOST
{{- if .Values.global.rabbitmq.host.value }}
          value: "{{ .Values.global.rabbitmq.host.value }}"
{{- else }}
          value: "{{ .Release.Name }}-rabbitmq"
{{- end }}
        - name: SPRING_RABBITMQ_USERNAME
          value: {{ .Values.global.rabbitmq.username.value }}
        - name: SPRING_RABBITMQ_PASSWORD
          value: {{ .Values.global.rabbitmq.password.value }}
{{- if .Values.global.keycloak.url }}
        - name: ACT_KEYCLOAK_URL
          value: "{{ .Values.global.keycloak.url }}"
{{- end }}
{{- if .Values.db.deployPostgres }}
        - name: SPRING_DATASOURCE_URL
  {{- if .Values.db.uri }}
          value: "{{ .Values.db.uri }}"
  {{- else }}
          value: "jdbc:postgresql://{{ .Release.Name }}-{{ .Values.db.name }}:{{ .Values.db.port }}/postgres"
  {{- end }}
        - name: SPRING_DATASOURCE_DRIVER_CLASS_NAME
          value: {{ default "org.postgresql.Driver" .Values.db.driver }}
        - name: SPRING_DATASOURCE_USERNAME
          value: {{ default "postgres" .Values.db.user }}
        - name: SPRING_DATASOURCE_PASSWORD
  {{- if .Values.db.pass }}
          value: "{{ .Values.db.pass }}"
  {{ else }}
          valueFrom:
            secretKeyRef:
              name: {{ .Release.Name }}-{{ .Values.db.name }}
              key: postgres-password
  {{- end }}
        - name: SPRING_JPA_DATABASE_PLATFORM
          value: {{ default "org.hibernate.dialect.PostgreSQLDialect" .Values.db.platform }}
{{- end }}
        - name: EUREKA_CLIENT_ENABLED
          value: "false"
        - name: ACTIVITI_CLOUD_SERVICES_METADATA_EUREKA_STATIC_ENABLED
          value: "false"
        - name: ACTIVITI_CLOUD_SERVICES_METADATA_EUREKA_DYNAMIC_ENABLED
          value: "false"
        - name: ACT_CLOUD_CONFIG_SERVER_ENABLED
          value: "false"
{{- with .Values.extraEnv }}
{{ tpl . $ | indent 8 }}
{{- end }}
        ports:
        - containerPort: {{ .Values.service.internalPort }}
        livenessProbe:
          httpGet:
            path: {{ .Values.probePath }}
            port: {{ .Values.service.internalPort }}
          initialDelaySeconds: {{ .Values.livenessProbe.initialDelaySeconds }}
          periodSeconds: {{ .Values.livenessProbe.periodSeconds }}
          successThreshold: {{ .Values.livenessProbe.successThreshold }}
          timeoutSeconds: {{ .Values.livenessProbe.timeoutSeconds }}
          failureThreshold: {{ .Values.livenessProbe.failureThreshold }}
        readinessProbe:
          httpGet:
            path: {{ .Values.probePath }}
            port: {{ .Values.service.internalPort }}
          periodSeconds: {{ .Values.readinessProbe.periodSeconds }}
          successThreshold: {{ .Values.readinessProbe.successThreshold }}
          timeoutSeconds: {{ .Values.readinessProbe.timeoutSeconds }}
          initialDelaySeconds: {{ .Values.readinessProbe.initialDelaySeconds }}
          failureThreshold: {{ .Values.livenessProbe.failureThreshold }}
        resources:
{{ toYaml .Values.resources | indent 12 }}
      terminationGracePeriodSeconds: {{ .Values.terminationGracePeriodSeconds }}
{{- if .Values.serviceAccount.create }}
      serviceAccountName: {{ .Values.service.name }}
{{- end }}